### ISSUE TITLE
BasicCrafting and Genome at GenomeAuthoritySystem

### ISSUE THREAD

**Issue by DarkWeird** [Terasology/SimpleFarming#119]
`Genome` and `BasicCrafting` modules is optional dependencies for `SimpleFarming`.
Both modules using at `GenomeAuthoritySystem`, 
then `GenomeAuthoritySystem` loads(works) when both modules is active.

Suggestions: 
1. extract `BasicCrafting` usage from `GenomeAuthoritySystem`, if `BasicCrafting` and `Genome` can be using separately there.
2. or enrich class with java docs, which explain that this system using both modules together only.

**Comment by skaldarnar** [comment]
The only event handler integrating with Basic Crafting is `onRecipeCraftedEvent`, which only works if Genome is also active.

https://github.com/Terasology/SimpleFarming/blob/b3c691b0cc50c74cdcbdafbf39cb0e82da589460/src/main/java/org/terasology/simpleFarming/systems/GenomeAuthoritySystem.java#L143-L164

We can split this system into two:

- `GenomeExtensionAuthoritySystem` (works if at least Genome is loaded)
- `GenomeCraftingExtensionAuthoritySystem` (works if both Genome and Basic Crafting are loaded)

I haven't looked at the details to figure out whether the genome-only features only make sense if crafting is also enabled, though.
