### ISSUE TITLE
Convert plants/crops to the correct plant types.

### ISSUE THREAD

**Issue by smsunarto** [Terasology/SimpleFarming#39]
With the new plant types added,

- Trees
- Vines

We should probably also convert plans/crops that should belong to those new plant types but are still in "bush" plant types. I'll create a list of plans that should be considered for conversion.

- [x] Orange Bush -> Orange Tree
- [x] Grape Bush -> Grape Vine
- [ ] Pear Bush -> Pear Tree
- [ ] Watermelon Bush -> Watermelon Vine

**Comment by jellysnake** [comment]
Closing this as a mixture of solved and no longer being fully relevant
