### ISSUE TITLE
Right-clicking with berry on bush makes berry disappear

### ISSUE THREAD

**Issue by TimVerhaegen** [Terasology/SimpleFarming#62]
To reproduce:
Simply place down a seed on the ground and wait for it to grow (should be a couple of seconds).
When the bush has fully grown just pick a berry off the bush and right click with that berry on the bush. The berry shouldn't disappear but it does anyway even though there's no real reason for that.

What is wrong?
Berry disappears when interacting with a not fully-grown bush.
Appears to be an Apple issue. (the fruit not the brand)

Good luck!

**Comment by jellysnake** [comment]
Okay, so this is intended behaviour. The apple currently has Hunger and Thirst components so it is consumed when you right click. If you harvest and apple bush and right click anywhere it'll consume it.
