### ISSUE TITLE
Move content to relevant submodules

### ISSUE THREAD

**Issue by jellysnake** [Terasology/SimpleFarming#66]
This module has a large amount of content and to break it up it should be moved to other sub modules.

Currently the split is as such:

# ~CommonEdibleFlora~
**This is done**

- [x] Apple
- [x] Banana
- [x] Blackberry
- [x] Carrot
- [x] Cherry
- [x] Grape
- [x] Orange
- [x] Pear
- [x] Starfuit

# AdditionalFruits

- [x] Blueberry
- [x] Cranberry
- [x] Gojiberry
- [x] Gooseberry
- [x] Strawberry
- [x] Raspberry
- [x] Guava
- [x] Peach
- [x] Pineapple
- [x] Watemelon
- [x] Melon
- [x] Passionfruit
- [x] Tomato

# AdditionalVegetables

- [x] Potato
- [x] Cucumber
- [x] Pumpkin
- [x] Squash

**Comment by jellysnake** [comment]
If you are here from GCI, please comment which items you are moving so other students don't also try and move them.

Also all of CommonEdibleFlora is done

**Comment by jellysnake** [comment]
Blueberry has been done

**Comment by FieryPhoenix909** [comment]
I'll move watermelon

**Comment by FieryPhoenix909** [comment]
I'll move strawberry

**Comment by FieryPhoenix909** [comment]
I will do strawberry

**Comment by njdom24** [comment]
I will do cranberry and gojiberry.

**Comment by FieryPhoenix909** [comment]
I will also do potato

**Comment by Maniacal7** [comment]
I'll do cucumber, pumpkin, and squash.

**Comment by zwliew** [comment]
I'll do Gooseberry.

**Comment by PAndaContron** [comment]
Guava and Peach are done.

**Comment by FieryPhoenix909** [comment]
Potato is done #77 #

**Comment by 15JMilroy** [comment]
I will do Pineapple and Watermelon

**Comment by lgnashold** [comment]
I will do Melon, Passionfruit and Tomato.

**Comment by PAndaContron** [comment]
Someone added Pineapple, check it off now.

**Comment by SurajDatta** [comment]
some also added Watermelon, please check it off now.

**Comment by jellysnake** [comment]
Closing issue as completed
