### ISSUE TITLE
I have a proposal for the program.

### ISSUE THREAD

**Issue by yoonbincho** [Terasology/SimpleFarming#87]
I am a Korean who is interested in this program. I'd like to help you complete the program. Can I suggest ideas on how to grow plants and the differentiation of plants? If you are interested in the Korean version, you can translate it into Korean. How is it?

**Comment by Cervator** [comment]
Belated hello there @yoonbincho - sorry for not responding to this for ages, but it isn't really the normal workflow to submit an issue to ask if you can help. Much better to join our Discord (https://discord.gg/terasology) or post in the forum (likely longer response time than chat tho), if you're still interested this long after :-)
